version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: 
          name: "Add fake sacct to env"
          command: echo "export PATH=.:$PATH" >> $BASH_ENV
      - run: 
          command: mkdir test-reports
      - run:
          name: Help Test 
          command: ./seff-array.py -h
      - run: 
          name: Single Job, Completed
          command: ./compare.sh 57336850
      - run: 
          name: Single Job, Failed
          command: ./compare.sh 57278179
      - run: 
          name: Single Job, Pending
          command: ./compare.sh 57339555
      - run: 
          name: Single Job, Running
          command: ./compare.sh 57340046
      - run: 
          name: Multiple Jobs, All Completed
          command: ./compare.sh 57340052
      - run: 
          name: Multiple Jobs, All Running
          command: ./compare.sh 57340029
      - run: 
          name: Multiple Jobs, Mixed States
          command: ./compare.sh 57169427
      - run: 
          name: Single Job, Invalid
          command: ./compare.sh 0
      - run:
          name: Sacct Failure
          command: ./compare.sh fail
      - store_test_results:
          path: test-reports/

workflows:
  main:
    jobs:
      - test